-------------------------------------------------------------------------------
-- TurismoUQ · Script DDL (Entrega 1)
-- Bases de Datos II · Universidad del Quindío
-- Motor: Oracle XE 21c
--
-- Orden de creación: primero las tablas sin dependencias (catálogos),
-- luego las que dependen de ellas, respetando las llaves foráneas.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. MUNICIPIO
-- Los 12 municipios del Quindío donde operan los alojamientos.
--------------------------------------------------------------------------------
CREATE TABLE municipio (
    id_municipio    NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(60)    NOT NULL,
    CONSTRAINT pk_municipio PRIMARY KEY (id_municipio),
    CONSTRAINT uq_municipio_nombre UNIQUE (nombre)
);

COMMENT ON TABLE municipio IS 'Municipios del Quindío donde se ofrece alojamiento.';

--------------------------------------------------------------------------------
-- 2. TIPO_ALOJAMIENTO
-- Catálogo abierto: finca cafetera, hotel, glamping, hostal, u otros que se
-- puedan sustentar. Es tabla y no un CHECK porque la lista puede crecer.
--------------------------------------------------------------------------------
CREATE TABLE tipo_alojamiento (
    id_tipo_alojamiento NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(40)    NOT NULL,
    CONSTRAINT pk_tipo_alojamiento PRIMARY KEY (id_tipo_alojamiento),
    CONSTRAINT uq_tipo_alojamiento_nombre UNIQUE (nombre)
);

COMMENT ON TABLE tipo_alojamiento IS 'Tipos de alojamiento (finca cafetera, hotel, glamping, hostal, otros).';

--------------------------------------------------------------------------------
-- 3. ALOJAMIENTO
-- Cada alojamiento pertenece a un municipio y a un tipo. La calificación es
-- la que el propio alojamiento se autoasigna al registrarse.
--------------------------------------------------------------------------------
CREATE TABLE alojamiento (
    id_alojamiento      NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre_comercial    VARCHAR2(120)   NOT NULL,
    direccion           VARCHAR2(160)   NOT NULL,
    calificacion        NUMBER(2,1)     NOT NULL,
    telefono            VARCHAR2(20),
    correo              VARCHAR2(100),
    id_municipio        NUMBER          NOT NULL,
    id_tipo_alojamiento NUMBER          NOT NULL,
    CONSTRAINT pk_alojamiento PRIMARY KEY (id_alojamiento),
    CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio)
        REFERENCES municipio (id_municipio),
    CONSTRAINT fk_alojamiento_tipo FOREIGN KEY (id_tipo_alojamiento)
        REFERENCES tipo_alojamiento (id_tipo_alojamiento),
    CONSTRAINT ck_alojamiento_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);

COMMENT ON TABLE alojamiento IS 'Alojamientos registrados en la plataforma (fincas, hoteles, glampings, hostales, etc.).';

--------------------------------------------------------------------------------
-- 4. HABITACION
-- Cada habitación pertenece a un único alojamiento. El número no se repite
-- dentro del mismo alojamiento (regla de negocio del enunciado).
-- El tipo se implementa como CHECK: es una lista cerrada que no va a crecer.
--------------------------------------------------------------------------------
CREATE TABLE habitacion (
    id_habitacion       NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    numero              VARCHAR2(10)    NOT NULL,
    capacidad_maxima    NUMBER(3)       NOT NULL,
    descripcion         VARCHAR2(200),
    tipo                VARCHAR2(10)    NOT NULL,
    id_alojamiento      NUMBER          NOT NULL,
    CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),
    CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento)
        REFERENCES alojamiento (id_alojamiento),
    CONSTRAINT uq_habitacion_numero UNIQUE (id_alojamiento, numero),
    CONSTRAINT ck_habitacion_capacidad CHECK (capacidad_maxima > 0),
    CONSTRAINT ck_habitacion_tipo CHECK (tipo IN ('SENCILLA','DOBLE','SUITE','CABANA'))
);

COMMENT ON TABLE habitacion IS 'Habitaciones ofrecidas por cada alojamiento.';

--------------------------------------------------------------------------------
-- 5. TEMPORADA
-- Las temporadas se definen por año: Semana Santa 2025 y Semana Santa 2026
-- son temporadas distintas, con fechas distintas.
--------------------------------------------------------------------------------
CREATE TABLE temporada (
    id_temporada    NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(60)    NOT NULL,
    nivel           VARCHAR2(10)    NOT NULL,
    fecha_inicio    DATE            NOT NULL,
    fecha_fin       DATE            NOT NULL,
    anio            NUMBER(4)       NOT NULL,
    CONSTRAINT pk_temporada PRIMARY KEY (id_temporada),
    CONSTRAINT ck_temporada_nivel CHECK (nivel IN ('ALTA','MEDIA','BAJA')),
    CONSTRAINT ck_temporada_fechas CHECK (fecha_fin >= fecha_inicio)
);

COMMENT ON TABLE temporada IS 'Temporadas (alta, media, baja) definidas por año, con su rango de fechas.';

--------------------------------------------------------------------------------
-- 6. TARIFA
-- Resuelve la relación N:M entre HABITACION y TEMPORADA. Cada combinación
-- habitación-temporada tiene su propio precio por noche (no es un porcentaje
-- fijo sobre un precio base). Ver decisión de diseño 3.2 del documento.
--------------------------------------------------------------------------------
CREATE TABLE tarifa (
    id_tarifa       NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    precio_noche    NUMBER(10,2)    NOT NULL,
    id_habitacion   NUMBER          NOT NULL,
    id_temporada    NUMBER          NOT NULL,
    CONSTRAINT pk_tarifa PRIMARY KEY (id_tarifa),
    CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion)
        REFERENCES habitacion (id_habitacion),
    CONSTRAINT fk_tarifa_temporada FOREIGN KEY (id_temporada)
        REFERENCES temporada (id_temporada),
    CONSTRAINT uq_tarifa_habitacion_temporada UNIQUE (id_habitacion, id_temporada),
    CONSTRAINT ck_tarifa_precio CHECK (precio_noche > 0)
);

COMMENT ON TABLE tarifa IS 'Precio por noche de cada habitación según la temporada vigente.';

--------------------------------------------------------------------------------
-- 7. CLIENTE
--------------------------------------------------------------------------------
CREATE TABLE cliente (
    id_cliente          NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre              VARCHAR2(120)   NOT NULL,
    documento_identidad VARCHAR2(20)    NOT NULL,
    correo              VARCHAR2(100),
    telefono            VARCHAR2(20),
    ciudad_origen       VARCHAR2(60),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cliente_documento UNIQUE (documento_identidad)
);

COMMENT ON TABLE cliente IS 'Clientes que realizan reservas en la plataforma.';

--------------------------------------------------------------------------------
-- 8. RESERVA
-- Cabecera de la reserva. El valor total NO se guarda aquí: se calcula a
-- partir de RESERVA_HABITACION, TARIFA y RESERVA_SERVICIO (ver fn_valor_estadia
-- en la Entrega 2).
--------------------------------------------------------------------------------
CREATE TABLE reserva (
    id_reserva      NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    fecha_checkin   DATE            NOT NULL,
    fecha_checkout  DATE            NOT NULL,
    estado          VARCHAR2(15)    DEFAULT 'PENDIENTE' NOT NULL,
    id_cliente      NUMBER          NOT NULL,
    CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente (id_cliente),
    CONSTRAINT ck_reserva_estado CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
    CONSTRAINT ck_reserva_fechas CHECK (fecha_checkout > fecha_checkin)
);

COMMENT ON TABLE reserva IS 'Reserva general hecha por un cliente; puede incluir una o varias habitaciones.';

--------------------------------------------------------------------------------
-- 9. RESERVA_HABITACION
-- Tabla intermedia que resuelve la relación N:M entre RESERVA y HABITACION.
-- Decisión de diseño 3.1: cada línea representa una habitación dentro de la
-- reserva, con sus propias fechas y número de huéspedes.
--------------------------------------------------------------------------------
CREATE TABLE reserva_habitacion (
    id_reserva_habitacion   NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    fecha_checkin           DATE            NOT NULL,
    fecha_checkout          DATE            NOT NULL,
    num_huespedes           NUMBER(3)       NOT NULL,
    id_reserva              NUMBER          NOT NULL,
    id_habitacion           NUMBER          NOT NULL,
    CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva_habitacion),
    CONSTRAINT fk_reshab_reserva FOREIGN KEY (id_reserva)
        REFERENCES reserva (id_reserva),
    CONSTRAINT fk_reshab_habitacion FOREIGN KEY (id_habitacion)
        REFERENCES habitacion (id_habitacion),
    CONSTRAINT ck_reshab_fechas CHECK (fecha_checkout > fecha_checkin),
    CONSTRAINT ck_reshab_huespedes CHECK (num_huespedes > 0)
);

COMMENT ON TABLE reserva_habitacion IS 'Detalle de habitaciones incluidas en una reserva, con sus propias fechas.';

--------------------------------------------------------------------------------
-- 10. SERVICIO
-- Cada servicio pertenece a un alojamiento específico (el desayuno del
-- Hotel X no es el mismo servicio que el del Hotel Y).
--------------------------------------------------------------------------------
CREATE TABLE servicio (
    id_servicio     NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(80)    NOT NULL,
    descripcion     VARCHAR2(200),
    precio          NUMBER(10,2)    NOT NULL,
    id_alojamiento  NUMBER          NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
    CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento)
        REFERENCES alojamiento (id_alojamiento),
    CONSTRAINT ck_servicio_precio CHECK (precio >= 0)
);

COMMENT ON TABLE servicio IS 'Servicios adicionales ofrecidos por cada alojamiento (desayuno, tours, transporte, etc.).';

--------------------------------------------------------------------------------
-- 11. RESERVA_SERVICIO
-- Tabla intermedia que resuelve la relación N:M entre RESERVA y SERVICIO.
-- precio_unitario congela el precio del servicio al momento de contratarlo.
--------------------------------------------------------------------------------
CREATE TABLE reserva_servicio (
    id_reserva_servicio NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    cantidad            NUMBER(3)       NOT NULL,
    precio_unitario     NUMBER(10,2)    NOT NULL,
    id_reserva          NUMBER          NOT NULL,
    id_servicio         NUMBER          NOT NULL,
    CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),
    CONSTRAINT fk_resserv_reserva FOREIGN KEY (id_reserva)
        REFERENCES reserva (id_reserva),
    CONSTRAINT fk_resserv_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio (id_servicio),
    CONSTRAINT ck_resserv_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_resserv_precio CHECK (precio_unitario >= 0)
);

COMMENT ON TABLE reserva_servicio IS 'Servicios adicionales contratados dentro de una reserva, con su cantidad.';

--------------------------------------------------------------------------------
-- 12. PAGO
-- Una reserva puede pagarse de una sola vez o en varios abonos.
--------------------------------------------------------------------------------
CREATE TABLE pago (
    id_pago     NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    fecha       DATE            NOT NULL,
    monto       NUMBER(10,2)    NOT NULL,
    metodo      VARCHAR2(20)    NOT NULL,
    estado      VARCHAR2(15)    DEFAULT 'PENDIENTE' NOT NULL,
    id_reserva  NUMBER          NOT NULL,
    CONSTRAINT pk_pago PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva)
        REFERENCES reserva (id_reserva),
    CONSTRAINT ck_pago_metodo CHECK (metodo IN ('TARJETA_CREDITO','TARJETA_DEBITO','PSE','TRANSFERENCIA','EFECTIVO')),
    CONSTRAINT ck_pago_estado CHECK (estado IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
    CONSTRAINT ck_pago_monto CHECK (monto > 0)
);

COMMENT ON TABLE pago IS 'Pagos o abonos realizados sobre una reserva.';

--------------------------------------------------------------------------------
-- 13. RESENA
-- Un cliente solo puede reseñar un alojamiento tras una estadía completada;
-- por eso lleva id_reserva como referencia a la estadía que la origina, y esa
-- columna es única: una reserva da lugar, como máximo, a una reseña.
--------------------------------------------------------------------------------
CREATE TABLE resena (
    id_resena       NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    calificacion    NUMBER(1)       NOT NULL,
    comentario      VARCHAR2(500),
    fecha           DATE            DEFAULT SYSDATE NOT NULL,
    id_cliente      NUMBER          NOT NULL,
    id_alojamiento  NUMBER          NOT NULL,
    id_reserva      NUMBER          NOT NULL,
    CONSTRAINT pk_resena PRIMARY KEY (id_resena),
    CONSTRAINT fk_resena_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente (id_cliente),
    CONSTRAINT fk_resena_alojamiento FOREIGN KEY (id_alojamiento)
        REFERENCES alojamiento (id_alojamiento),
    CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva)
        REFERENCES reserva (id_reserva),
    CONSTRAINT uq_resena_reserva UNIQUE (id_reserva),
    CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);

COMMENT ON TABLE resena IS 'Reseña dejada por un cliente sobre un alojamiento, ligada a una reserva completada.';

--------------------------------------------------------------------------------
-- 14. USUARIO_SISTEMA
-- id_alojamiento queda nulo cuando el usuario es administrador de la
-- plataforma (no pertenece a ningún alojamiento específico).
--------------------------------------------------------------------------------
CREATE TABLE usuario_sistema (
    id_usuario      NUMBER          GENERATED BY DEFAULT AS IDENTITY,
    nombre_usuario  VARCHAR2(40)    NOT NULL,
    nombre          VARCHAR2(120)   NOT NULL,
    correo          VARCHAR2(100)   NOT NULL,
    rol             VARCHAR2(20)    NOT NULL,
    id_alojamiento  NUMBER,
    CONSTRAINT pk_usuario_sistema PRIMARY KEY (id_usuario),
    CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento)
        REFERENCES alojamiento (id_alojamiento),
    CONSTRAINT uq_usuario_nombre_usuario UNIQUE (nombre_usuario),
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMINISTRADOR','ENCARGADO'))
);

COMMENT ON TABLE usuario_sistema IS 'Usuarios internos de la plataforma: administradores y encargados de alojamiento.';

--------------------------------------------------------------------------------
-- Fin del script DDL
--------------------------------------------------------------------------------

